import Hero from "@/components/common/hero/Hero";
import Gallery from "@/components/work/gallery/Gallery";
import Head from "next/head";

export default function Work() {
  return (
    <>
      <Head>
        <title>Work</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="main">
        <Hero paragraph={"Something about my job or whatever"} />
        <Gallery />
      </main>
    </>
  );
}
