import Head from "next/head";

export default function Work() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>work</main>
    </>
  );
}
